app = "expense-calculator"
primary_region = "sin"

[env]
NODE_ENV = "production"
PORT = "3000"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[env.production]
NODE_ENV = "production"
